### ISSUE TITLE
No Terms and Conditions

### ISSUE THREAD

**Issue by RedVortexDev** [AmberWat/NegativeSpaceFont#3]
How am i supposed to know how can I use this and how can I distribute it?

**Comment by AmberWat** [comment]
You just download [a release](https://github.com/AmberWat/NegativeSpaceFont/releases/) load it like any other resource pack. Most creators end up merging it into the pack they're using for a project and leaving a line crediting my project in a text file. I'm happy with that.

Once it is active you insert either the raw characters or use the translations in text that's being displayed somewhere (see [readme](https://github.com/AmberWat/NegativeSpaceFont/blob/master/README.md)).

The character codes and translations are provided in a format compatible with the `tellraw` command, ready to be inserted. If you want to use it from something like a mod or server plugin written in Java then the character codes should still work but you'd need to check how to construct the equivalent translation components.

*Need the character codes in a different format? Try [this site](https://r12a.github.io/app-conversion/).*

The terms for distribution are laid out in [the included license](https://github.com/AmberWat/NegativeSpaceFont/blob/master/LICENSE.txt). Simply, you are allowed to distribute and even modify it as long as you leave some basic credit.

**Comment by RedVortexDev** [comment]
i forgot i made this :dizzy_face: 
apologies
