### ISSUE TITLE
 LICENSE

### ISSUE THREAD

**Issue by Waradu** [AmberWat/NegativeSpaceFont#9]
I don't know much about licenses so my question is can I use the texture pack for my own adventure maps even if I publish them? 
(with credits of course)

**Comment by AmberWat** [comment]
Yes you can. I suggest leaving a copyright notice in a credits or license file in your pack. Something like this would do:
```
Includes Negative Space Font Copyright (c) 2020 AmberW licensed under Creative Commons Attribution 4.0 International
```
You are then free to edit and distribute my pack within yours, even for commercial use. I'm not picky about crediting beyond that, but it is very appreciated, especially links back to the GitHub page.

**Comment by Waradu** [comment]
Thank you. I'll be sure to add credits if I ever post something to public.
